image: ghcr.io/cirruslabs/flutter:3.38.7

definitions:
  steps:
    - step: &running-ci
        name: CI.
        script:
          - flutter doctor -v
          - make tcl force=true
          - make sync
          - make check_ci

pipelines:
  pull-requests:
    '**':
      - step: *running-ci
